name: "opensyd_angular"
version: 3.0.0
description: Opensyd AngularDart libs
author: Sergio Lisan <sels@venosyd.com>
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  angular: 
  angular_forms: 
  opensyd_dart:
    git: https://github.com/venosyd/opensyd_dart

dev_dependencies:
  build_runner: 
  build_web_compilers: 
